from . import UserSchema
from . import ChatPhotoSchema
from . import ChatSchema
from . import MessageSchema
from . import UserSchema
from . import MessageEntitySchema
from . import AudioSchema
from . import DocumentSchema
from . import StickerSchema
from . import GameSchema
from . import PhotoSizeSchema
from . import VideoSchema
from . import VoiceSchema
from . import VideoNoteSchema
from . import ContactSchema
from . import LocationSchema
from . import VenueSchema
from . import InvoiceSchema
from . import SuccessfulPaymentSchema
from . import MaskPosition
from . import AnimationSchema
from . import ShippingAddressSchema
from . import OrderInfoSchema
from . import InlineQuerySchema
from . import ChosenInlineResultSchema
from . import CallbackQuerySchema
from . import ShippingQuerySchema
from . import PreCheckoutQuerySchema
from . import ErrorSchema
from . import InlineKeyboardButtonSchema
from . import InlineKeyboardMarkupSchema


